import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import type { TransactionHistoryItem, RentHistoryItem } from './additionalInfoStorage';

// Augment jsPDF type to include lastAutoTable from jspdf-autotable
declare module 'jspdf' {
  interface jsPDF {
    lastAutoTable?: {
      finalY: number;
    };
  }
}

function formatAmount(n: number) {
  return new Intl.NumberFormat(undefined, { style: 'currency', currency: 'BDT' }).format(n);
}

function formatDate(d: string) {
  try {
    return new Date(d).toLocaleDateString();
  } catch {
    return d;
  }
}

function addPageNumbers(doc: jsPDF, margin: number) {
  const pageCount = doc.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    const pageWidth = doc.internal.pageSize.getWidth();
    const pageHeight = doc.internal.pageSize.getHeight();
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(9);
    doc.setTextColor(120, 120, 120);
    doc.text(`Page ${i} of ${pageCount}`, pageWidth - margin, pageHeight - 10, { align: 'right' });
  }
}

function ensureSpaceOrAddPage(doc: jsPDF, y: number, margin: number, needed = 18) {
  const pageHeight = doc.internal.pageSize.getHeight();
  if (y + needed > pageHeight - margin) {
    doc.addPage();
    return margin;
  }
  return y;
}

// Independent PDF: History of Transaction only
export function generateTransactionReport(transactions: TransactionHistoryItem[]) {
  const doc = new jsPDF({ unit: 'pt', format: 'a4' });
  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 40;

  // Title
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(20);
  doc.setTextColor(0, 0, 0);
  doc.text("Prantor's House", pageWidth / 2, margin, { align: 'center' });

  // Subtitle
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(12);
  doc.setTextColor(102, 102, 102);
  const subtitleY = margin + 20;
  doc.text(`Generated on: ${new Date().toLocaleString()}`, pageWidth / 2, subtitleY, { align: 'center' });

  // Section: History of Transaction
  let cursorY = subtitleY + 28;
  doc.setTextColor(0, 0, 0);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(14);
  doc.text('History of Transaction', margin, cursorY);

  const txBody = (transactions ?? []).map((t, idx) => [String(idx + 1), t.name, formatAmount(t.amount)]);

  autoTable(doc, {
    startY: cursorY + 8,
    headStyles: { fillColor: [33, 150, 243], textColor: 255, halign: 'left' },
    bodyStyles: { textColor: 50 },
    styles: {
      font: 'helvetica',
      fontSize: 11,
      cellPadding: 6,
      lineColor: [230, 230, 230],
      lineWidth: 0.8,
    },
    head: [['Serial No', 'Name of Transaction', 'Amount']],
    body: txBody,
    theme: 'grid',
    margin: { left: margin, right: margin, top: margin, bottom: margin },
    pageBreak: 'auto',
  });

  cursorY = (doc.lastAutoTable?.finalY ?? cursorY) + 20;

  // Total (Transactions only)
  const totalTx = (transactions ?? []).reduce((sum, t) => sum + (t.amount || 0), 0);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(14);
  doc.setTextColor(0, 0, 0);

  cursorY = ensureSpaceOrAddPage(doc, cursorY, margin, 18);
  doc.text(`Total Amount: ${formatAmount(totalTx)}`, margin, cursorY);

  // Footer
  cursorY = ensureSpaceOrAddPage(doc, cursorY + 12, margin, 14);
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(10);
  doc.setTextColor(119, 119, 119);
  doc.text('Report generated by Expense Tracker', margin, cursorY + 12);

  // Page numbers
  addPageNumbers(doc, margin);

  doc.save('Prantors_House_History_of_Transaction.pdf');
}

// Independent PDF: History of House Rent only (Deed notes at the end)
export function generateRentReport(rents: RentHistoryItem[]) {
  const doc = new jsPDF({ unit: 'pt', format: 'a4' });
  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 40;

  // Title
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(20);
  doc.setTextColor(0, 0, 0);
  doc.text("Prantor's House", pageWidth / 2, margin, { align: 'center' });

  // Subtitle
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(12);
  doc.setTextColor(102, 102, 102);
  const subtitleY = margin + 20;
  doc.text(`Generated on: ${new Date().toLocaleString()}`, pageWidth / 2, subtitleY, { align: 'center' });

  // Section: History of House Rent
  let cursorY = subtitleY + 28;
  doc.setTextColor(0, 0, 0);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(14);
  doc.text('History of House Rent', margin, cursorY);

  // Table WITHOUT deed column; deed notes will be placed at the end
  const rentBody = (rents ?? []).map((r) => [r.month, formatAmount(r.amount), formatDate(r.date)]);

  autoTable(doc, {
    startY: cursorY + 8,
    headStyles: { fillColor: [16, 185, 129], textColor: 255, halign: 'left' },
    bodyStyles: { textColor: 50 },
    styles: {
      font: 'helvetica',
      fontSize: 11,
      cellPadding: 6,
      lineColor: [230, 230, 230],
      lineWidth: 0.8,
    },
    head: [['Month', 'Amount', 'Date']],
    body: rentBody,
    theme: 'grid',
    margin: { left: margin, right: margin, top: margin, bottom: margin },
    pageBreak: 'auto',
  });

  cursorY = (doc.lastAutoTable?.finalY ?? cursorY) + 20;

  // Total (House Rent only)
  const totalRent = (rents ?? []).reduce((sum, r) => sum + (r.amount || 0), 0);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(14);
  doc.setTextColor(0, 0, 0);

  cursorY = ensureSpaceOrAddPage(doc, cursorY, margin, 18);
  doc.text(`Total Amount: ${formatAmount(totalRent)}`, margin, cursorY);

  // Deed With Homeowner (must be the last section of the PDF)
  const notes = (rents ?? [])
    .map((r) => ({ month: r.month, note: (r.deedNote ?? '').trim() }))
    .filter((x) => x.note.length > 0);

  const deedStartY = cursorY + 24;
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(14);

  let y = ensureSpaceOrAddPage(doc, deedStartY, margin, 18);
  doc.text('Deed With Homeowner', margin, y);

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(11);
  doc.setTextColor(51, 51, 51);
  y += 10;

  if (notes.length === 0) {
    y = ensureSpaceOrAddPage(doc, y, margin, 16);
    doc.text('No deed notes provided.', margin, y);
  } else {
    const textWidth = pageWidth - margin * 2;
    notes.forEach((n, idx) => {
      const line = `${idx + 1}. ${n.month}: ${n.note}`;
      const lines = doc.splitTextToSize(line, textWidth);
      lines.forEach((l) => {
        y = ensureSpaceOrAddPage(doc, y, margin, 16);
        doc.text(l, margin, y);
        y += 16;
      });
      y += 4;
    });
  }

  // Footer (place on current page with safe spacing)
  y = ensureSpaceOrAddPage(doc, y + 6, margin, 14);
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(10);
  doc.setTextColor(119, 119, 119);
  doc.text('Report generated by Expense Tracker', margin, y + 12);

  // Page numbers
  addPageNumbers(doc, margin);

  doc.save('Prantors_House_History_of_House_Rent.pdf');
}