import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import type { TransactionHistoryItem, RentHistoryItem } from '@/lib/additionalInfoStorage';

// Augment jsPDF type to include lastAutoTable from jspdf-autotable
declare module 'jspdf' {
  interface jsPDF {
    lastAutoTable?: {
      finalY: number;
    };
  }
}

// Generate ONE combined PDF report with both tables and a total amount
export function generateCombinedReport(
  transactions: TransactionHistoryItem[],
  rents: RentHistoryItem[]
) {
  const doc = new jsPDF({ unit: 'pt', format: 'a4' });
  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 40;

  // Title
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(20);
  doc.text("Prantor's House", pageWidth / 2, margin, { align: 'center' });

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(12);
  doc.setTextColor('#666666');
  const subtitleY = margin + 20;
  doc.text(`Generated on: ${new Date().toLocaleString()}`, pageWidth / 2, subtitleY, { align: 'center' });

  // Spacer
  let cursorY = subtitleY + 20;

  // Section 1: History of Transaction
  doc.setTextColor('#000000');
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(14);
  doc.text('History of Transaction', margin, cursorY);

  const txBody = (transactions ?? []).map((t, idx) => [String(idx + 1), t.name, formatAmount(t.amount)]);

  autoTable(doc, {
    startY: cursorY + 8,
    headStyles: { fillColor: [33, 150, 243], textColor: 255, halign: 'left' },
    bodyStyles: { textColor: 50 },
    styles: {
      font: 'helvetica',
      fontSize: 11,
      cellPadding: 6,
      lineColor: [230, 230, 230],
      lineWidth: 0.8,
    },
    head: [['Serial No', 'Name of Transaction', 'Amount']],
    body: txBody,
    theme: 'grid',
    margin: { left: margin, right: margin },
  });

  cursorY = (doc.lastAutoTable?.finalY ?? cursorY) + 20;

  // Section 2: History of House Rent
  doc.setTextColor('#000000');
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(14);
  doc.text('History of House Rent', margin, cursorY);

  const rentBody = (rents ?? []).map((r) => [r.month, formatAmount(r.amount), formatDate(r.date), r.deedNote || '']);

  autoTable(doc, {
    startY: cursorY + 8,
    headStyles: { fillColor: [16, 185, 129], textColor: 255, halign: 'left' },
    bodyStyles: { textColor: 50 },
    styles: {
      font: 'helvetica',
      fontSize: 11,
      cellPadding: 6,
      lineColor: [230, 230, 230],
      lineWidth: 0.8,
    },
    head: [['Month', 'Amount', 'Date', 'Deed With Homeowner']],
    body: rentBody,
    theme: 'grid',
    margin: { left: margin, right: margin },
  });

  cursorY = (doc.lastAutoTable?.finalY ?? cursorY) + 20;

  // Total Amount from both tables
  const totalAmount =
    (transactions ?? []).reduce((sum, t) => sum + (t.amount || 0), 0) +
    (rents ?? []).reduce((sum, r) => sum + (r.amount || 0), 0);

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(14);
  doc.setTextColor('#000000');
  doc.text(`Total Amount: ${formatAmount(totalAmount)}`, margin, cursorY);

  // Footer note
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(10);
  doc.setTextColor('#777777');
  doc.text('Report generated by Expense Tracker', margin, cursorY + 18);

  doc.save('Prantors_House_Report.pdf');
}

function formatAmount(n: number) {
  return new Intl.NumberFormat(undefined, { style: 'currency', currency: 'BDT' }).format(n);
}

function formatDate(d: string) {
  try {
    return new Date(d).toLocaleDateString();
  } catch {
    return d;
  }
}